databases:
  - name: smartseason-db
    plan: free

services:
  - type: web
    name: smartseason-backend
    runtime: node
    plan: free
    buildCommand: cd smartseason-backend && npm install && npm run prisma:generate && npm run build
    startCommand: cd smartseason-backend && npm run prisma:deploy && npm run start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: smartseason-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: 24h
      - key: FRONTEND_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false

  - type: web
    name: smartseason-frontend
    runtime: static
    buildCommand: cd smartseason-frontend && npm install && npm run build
    staticPublishPath: smartseason-frontend/dist/smartseason-frontend/browser
    envVars:
      - key: NODE_VERSION
        value: 20
    routes:
      - type: rewrite
        source: /*
        destination: /index.html